package vistas;

import dao.UsuarioDetalleDAO;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelos.Usuario;
import modelos.UsuarioDetalle;
import util.JPAUtil;

/**
 *
 * @author Eloym
 */
public class MenuUsuario extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario(Usuario usuarioSeleccionado) {
        this.usuario = usuarioSeleccionado;
        initComponents();
        maximizarVentanaConFondo();
        mostrarFoto(usuario.getImagenPerfil());
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredFondo = new javax.swing.JLayeredPane();
        btnPerfil = new javax.swing.JButton();
        btnBiblioteca = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblFotoUsuario = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPerfil.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        layeredFondo.add(btnPerfil);
        btnPerfil.setBounds(90, 120, 190, 100);

        btnBiblioteca.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        btnBiblioteca.setText("Biblioteca");
        btnBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecaActionPerformed(evt);
            }
        });
        layeredFondo.add(btnBiblioteca);
        btnBiblioteca.setBounds(90, 240, 190, 100);

        btnTienda.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        btnTienda.setText("Tienda");
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });
        layeredFondo.add(btnTienda);
        btnTienda.setBounds(90, 360, 190, 100);

        btnSalir.setFont(new java.awt.Font("Impact", 2, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        layeredFondo.add(btnSalir);
        btnSalir.setBounds(40, 630, 130, 80);
        layeredFondo.add(lblFotoUsuario);
        lblFotoUsuario.setBounds(30, 10, 90, 90);

        lblTitulo.setBackground(new java.awt.Color(0, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Impact", 2, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Bienvenido: " + usuario.getNombre());
        layeredFondo.add(lblTitulo);
        lblTitulo.setBounds(520, 30, 570, 120);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoInicial.jpg"))); // NOI18N
        layeredFondo.add(lblFondo);
        lblFondo.setBounds(0, 0, 1270, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal inicio = new VentanaPrincipal();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        // TODO add your handling code here:
        VentanaTienda venTienda = new VentanaTienda(usuario);
        venTienda.setVisible(true);
        venTienda.setLocationRelativeTo(null); // Para centrar la ventana
        dispose();

    }//GEN-LAST:event_btnTiendaActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        if (usuario.getUsuarioDetalle() == null) {
            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "No tienes un perfil creado. ¿Deseas crear uno ahora?",
                    "Perfil no encontrado",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {
                // Crear el detalle vacío
                UsuarioDetalle detalle = new UsuarioDetalle();
                detalle.setUsuario(usuario); // Asocia el detalle al usuario

                // Guardar en la base de datos
                UsuarioDetalleDAO detalleDAO = new UsuarioDetalleDAO(JPAUtil.getEntityManager());
                detalleDAO.insertar(detalle);

                // Asignar el detalle al usuario (opcional si la sesión lo requiere)
                usuario.setUsuarioDetalle(detalle);

                // Abrir la vista de perfil
                VistaPerfil vistaPerfil = new VistaPerfil(usuario);
                vistaPerfil.setVisible(true);
                vistaPerfil.setLocationRelativeTo(null);
            }
        } else {
            VistaPerfil vistaPerfil = new VistaPerfil(usuario);
            vistaPerfil.setVisible(true);
            vistaPerfil.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        // TODO add your handling code here:
        BibliotecaUsuario ventanaBiblioteca = new BibliotecaUsuario(usuario);
        ventanaBiblioteca.setVisible(true);
        ventanaBiblioteca.setLocationRelativeTo(this); // centrar
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    public void maximizarVentanaConFondo() {
        // Maximizamos la ventana (con bordes y barra de título)
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);

        // Ajustamos el tamaño de los componentes al tamaño actual de la ventana
        Dimension tamaño = this.getSize();
        layeredFondo.setBounds(0, 0, tamaño.width, tamaño.height);
        lblFondo.setBounds(0, 0, tamaño.width, tamaño.height);

        // Añadimos un listener para que cuando redimensiones la ventana,
        // el fondo y la tabla se ajusten automáticamente
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                Dimension tamaño = getSize();
                layeredFondo.setBounds(0, 0, tamaño.width, tamaño.height);
                lblFondo.setBounds(0, 0, tamaño.width, tamaño.height);
            }
        });
    }

    private void mostrarFoto(String ruta) {
        ImageIcon icon;

        if (ruta == null || ruta.trim().isEmpty()) {
            icon = new ImageIcon("imagenes/usuarios/defecto.png");
        } else {
            icon = new ImageIcon(ruta);
        }

        Image imagenEscalada = icon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        lblFotoUsuario.setIcon(new ImageIcon(imagenEscalada));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTienda;
    private javax.swing.JLayeredPane layeredFondo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFotoUsuario;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
