package vistas;

import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelos.Usuario;
import util.JPAUtil;

/**
 *
 * @author Eloym
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private List<Usuario> listaUsuarios;

    /**
     * Creates new form vistaInicial
     */
    public VentanaPrincipal() {
        initComponents();

        maximizarVentanaConFondo();

        tablaUsuarios.setOpaque(false);
        ((DefaultTableCellRenderer) tablaUsuarios.getDefaultRenderer(Object.class)).setOpaque(false);
        scrollUsuarios.setOpaque(false);
        scrollUsuarios.getViewport().setOpaque(false);
        cargarUsuariosEnTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredFondo = new javax.swing.JLayeredPane();
        btnCrearUsuario = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        scrollUsuarios = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearUsuario.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 255)));
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        layeredFondo.add(btnCrearUsuario);
        btnCrearUsuario.setBounds(420, 620, 210, 90);

        lblTitulo.setBackground(new java.awt.Color(0, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Impact", 2, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("ELIGE UN USUARIO CON DOBLE CLICK");
        layeredFondo.add(lblTitulo);
        lblTitulo.setBounds(490, 30, 570, 120);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoInicial.jpg"))); // NOI18N
        layeredFondo.add(lblFondo);
        lblFondo.setBounds(10, 0, 1270, 740);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollUsuarios.setViewportView(tablaUsuarios);

        layeredFondo.setLayer(scrollUsuarios, javax.swing.JLayeredPane.MODAL_LAYER);
        layeredFondo.add(scrollUsuarios);
        scrollUsuarios.setBounds(30, 20, 370, 910);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        FormularioRegistro formRegistro = new FormularioRegistro(this);
        formRegistro.setVisible(true);
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public void cargarUsuariosEnTabla() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                if (column == 1) {
                    return ImageIcon.class;
                }
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addColumn("Nombre");
        model.addColumn("Foto");

        UsuarioDAO usuarioDAO = new UsuarioDAO(JPAUtil.getEntityManager());

        for (Usuario u : usuarioDAO.listarTodos()) {
            String ruta = u.getImagenPerfil();
            ImageIcon icon;

            if (ruta == null || ruta.trim().isEmpty()) {
                icon = new ImageIcon("imagenes/usuarios/defecto.png");
            } else {
                icon = new ImageIcon(ruta);
            }

            Image img = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
            icon = new ImageIcon(img);

            model.addRow(new Object[]{u.getNombre(), icon});
        }

        tablaUsuarios.setRowHeight(45);
        tablaUsuarios.setModel(model);

        // Renderer para la primera columna
        DefaultTableCellRenderer nombreRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    c.setBackground(row % 2 == 0 ? new Color(235, 248, 255) : new Color(220, 236, 248));
                    c.setForeground(Color.BLACK);
                } else {
                    c.setBackground(new Color(100, 149, 237));
                    c.setForeground(Color.WHITE);
                }
                c.setFont(new Font("Impact", Font.PLAIN, 16));
                return c;
            }
        };

        tablaUsuarios.getColumnModel().getColumn(0).setCellRenderer(nombreRenderer);

        tablaUsuarios.getTableHeader().setReorderingAllowed(false);

        listaUsuarios = usuarioDAO.listarTodos();

        tablaUsuarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && !e.isConsumed()) {
                    e.consume();
                    int filaVista = tablaUsuarios.rowAtPoint(e.getPoint());
                    if (filaVista != -1) {
                        int filaModelo = tablaUsuarios.convertRowIndexToModel(filaVista);
                        Usuario usuarioSeleccionado = listaUsuarios.get(filaModelo);

                        MenuUsuario menu = new MenuUsuario(usuarioSeleccionado);
                        menu.setVisible(true);
                        dispose();
                    }
                }
            }
        });
    }

    public void maximizarVentanaConFondo() {
        // Maximizamos la ventana (con bordes y barra de título)
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);

        // Ajustamos el tamaño de los componentes al tamaño actual de la ventana
        Dimension tamaño = this.getSize();
        layeredFondo.setBounds(0, 0, tamaño.width, tamaño.height);
        lblFondo.setBounds(0, 0, tamaño.width, tamaño.height);

        // Añadimos un listener para que cuando redimensiones la ventana,
        // el fondo y la tabla se ajusten automáticamente
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                Dimension tamaño = getSize();
                layeredFondo.setBounds(0, 0, tamaño.width, tamaño.height);
                lblFondo.setBounds(0, 0, tamaño.width, tamaño.height);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JLayeredPane layeredFondo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
