package vistas;

import dao.UsuarioDAO;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelos.Usuario;
import util.JPAUtil;

/**
 *
 * @author Eloym
 */
public class vistaInicial extends javax.swing.JFrame {

    /**
     * Creates new form vistaInicial
     */
    public vistaInicial() {
        initComponents();
        
        maximizarVentanaConFondo();

        tablaUsuarios.setOpaque(false);
        ((DefaultTableCellRenderer) tablaUsuarios.getDefaultRenderer(Object.class)).setOpaque(false);
        scrollUsuarios.setOpaque(false);
        scrollUsuarios.getViewport().setOpaque(false);
        cargarUsuariosEnTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredFondo = new javax.swing.JLayeredPane();
        lblFondo = new javax.swing.JLabel();
        scrollUsuarios = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/fondoInicial.jpg"))); // NOI18N
        layeredFondo.add(lblFondo);
        lblFondo.setBounds(10, 0, 1270, 740);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollUsuarios.setViewportView(tablaUsuarios);

        layeredFondo.setLayer(scrollUsuarios, javax.swing.JLayeredPane.MODAL_LAYER);
        layeredFondo.add(scrollUsuarios);
        scrollUsuarios.setBounds(30, 20, 370, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaInicial().setVisible(true);
            }
        });
    }

    private void cargarUsuariosEnTabla() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int column) {
                // La segunda columna (índice 1) será una imagen
                if (column == 1) {
                    return ImageIcon.class;
                }
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tabla no editable
            }
        };

        model.addColumn("Nombre");
        model.addColumn("Foto");

        UsuarioDAO usuarioDAO = new UsuarioDAO(JPAUtil.getEntityManager());

        for (Usuario u : usuarioDAO.listarTodos()) {
            // Determinar ruta de imagen
            String ruta = u.getImagenPerfil();
            ImageIcon icon;

            if (ruta == null || ruta.trim().isEmpty()) {
                // Usar imagen por defecto
                icon = new ImageIcon("imagenes/usuarios/defecto.png");
            } else {
                // Usar imagen del usuario
                icon = new ImageIcon(ruta);
            }

            // Escalar imagen
            Image img = icon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
            icon = new ImageIcon(img);

            model.addRow(new Object[]{u.getNombre(), icon});
        }

        tablaUsuarios.setRowHeight(45);
        tablaUsuarios.setModel(model);
    }

public void maximizarVentanaConFondo() {
    // Maximizamos la ventana (con bordes y barra de título)
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    this.setVisible(true);

    // Ajustamos el tamaño de los componentes al tamaño actual de la ventana
    Dimension tamaño = this.getSize();
    layeredFondo.setBounds(0, 0, tamaño.width, tamaño.height);
    lblFondo.setBounds(0, 0, tamaño.width, tamaño.height);

    // Añadimos un listener para que cuando redimensiones la ventana,
    // el fondo y la tabla se ajusten automáticamente
    this.addComponentListener(new ComponentAdapter() {
        @Override
        public void componentResized(ComponentEvent e) {
            Dimension tamaño = getSize();
            layeredFondo.setBounds(0, 0, tamaño.width, tamaño.height);
            lblFondo.setBounds(0, 0, tamaño.width, tamaño.height);
        }
    });
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layeredFondo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
